#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTAINER_NAME="ai-container"

PUID=$(id -u)
PGID=$(id -g)
TZ=Asia/Shanghai
export PUID PGID TZ

# Function to print colored messages
info_msg() {
    echo -e "${BLUE}ℹ${NC} $1"
}

success_msg() {
    echo -e "${GREEN}✓${NC} $1"
}

warning_msg() {
    echo -e "${YELLOW}⚠${NC} $1"
}

error_exit() {
    echo -e "${RED}✗ Error: $1${NC}" >&2
    exit 1
}

# Function to trim whitespace
trim() {
    local var="$1"
    # Remove leading whitespace
    var="${var#"${var%%[![:space:]]*}"}"
    # Remove trailing whitespace
    var="${var%"${var##*[![:space:]]}"}"
    echo -n "$var"
}

# =============================================================================
# Environment Variable Validation System
# =============================================================================

# Required environment variables for .env file
# Format: "VAR_NAME|PROMPT_MESSAGE|PLACEHOLDER_VALUE"
declare -a REQUIRED_ENV_VARS=(
    "GITHUB_TOKEN|GitHub Token (用于访问特定代码仓库)|your_github_token_here"
    "OPENCODE_SERVER_USERNAME|OpenCode Server Username (Web登录用户名)|"
    "OPENCODE_SERVER_PASSWORD|OpenCode Server Password (Web登录密码)|"
)

# Helper: Get value from .env file
# Args: $1 = variable name
# Returns: value (empty if not found)
get_env_value() {
    local var_name="$1"
    local value=""
    
    if [ -f "$ENV_FILE" ]; then
        if grep -q "^${var_name}=" "$ENV_FILE" 2>/dev/null; then
            value=$(grep "^${var_name}=" "$ENV_FILE" | cut -d'=' -f2-)
            value=$(trim "$value")
        fi
    fi
    
    echo -n "$value"
}

# Helper: Prompt user for input with validation
# Args: $1 = prompt message
# Returns: trimmed user input
prompt_for_value() {
    local prompt_msg="$1"
    local input=""
    
    while true; do
        read -p "$prompt_msg: " input
        input=$(trim "$input")
        
        if [ -z "$input" ]; then
            warning_msg "值不能为空，请重新输入"
            continue
        fi
        
        echo -n "$input"
        return 0
    done
}

# Helper: Update .env file with new value
# Args: $1 = variable name, $2 = value
update_env_file() {
    local var_name="$1"
    local value="$2"
    
    # Create .env file if not exists
    if [ ! -f "$ENV_FILE" ]; then
        echo "# Environment Configuration" > "$ENV_FILE"
        echo "# Generated by start.sh" >> "$ENV_FILE"
        echo "" >> "$ENV_FILE"
    fi
    
    # Remove existing line if exists
    if grep -q "^${var_name}=" "$ENV_FILE" 2>/dev/null; then
        grep -v "^${var_name}=" "$ENV_FILE" > "${ENV_FILE}.tmp" || true
        mv "${ENV_FILE}.tmp" "$ENV_FILE"
    fi
    
    # Add new value
    echo "${var_name}=${value}" >> "$ENV_FILE"
}

# Validate all .env file variables
validate_env_file_vars() {
    local missing_vars=()
    local prompts=()
    
    for entry in "${REQUIRED_ENV_VARS[@]}"; do
        IFS='|' read -r var_name prompt_msg placeholder <<< "$entry"
        
        local current_value=$(get_env_value "$var_name")
        
        if [ -z "$current_value" ] || [ "$current_value" = "$placeholder" ]; then
            missing_vars+=("$var_name")
            prompts+=("$prompt_msg")
        else
            success_msg "$var_name found in .env"
        fi
    done
    
    if [ ${#missing_vars[@]} -gt 0 ]; then
        echo ""
        warning_msg "以下环境变量需要配置:"
        for i in "${!missing_vars[@]}"; do
            info_msg "  - ${missing_vars[$i]}: ${prompts[$i]}"
        done
        echo ""
        
        for i in "${!missing_vars[@]}"; do
            local var_name="${missing_vars[$i]}"
            local prompt_msg="${prompts[$i]}"
            
            if [ "$var_name" = "GITHUB_TOKEN" ]; then
                info_msg "Create token at: https://github.com/settings/tokens"
            fi
            
            local value=$(prompt_for_value "$prompt_msg")
            update_env_file "$var_name" "$value"
            success_msg "$var_name saved to .env"
        done
    fi
}

# Validate auth.json API key
validate_auth_json_key() {
    local AUTH_DIR="$SCRIPT_DIR/data/home/.local/share/opencode"
    local AUTH_FILE="$AUTH_DIR/auth.json"
    local NEED_API_KEY=false
    
    info_msg "Checking API key configuration..."
    
    # Create directory if not exists
    mkdir -p "$AUTH_DIR"
    
    # Check if auth.json exists and has valid keys
    if [ ! -f "$AUTH_FILE" ]; then
        NEED_API_KEY=true
        info_msg "auth.json not found"
    else
        # Check if file contains valid keys for both providers
        if ! grep -q '"zai-coding-plan"' "$AUTH_FILE" 2>/dev/null; then
            NEED_API_KEY=true
            info_msg "zai-coding-plan not found in auth.json"
        elif ! grep -q '"zhipuai-coding-plan"' "$AUTH_FILE" 2>/dev/null; then
            NEED_API_KEY=true
            info_msg "zhipuai-coding-plan not found in auth.json"
        else
            # Check if keys are non-empty
            local ZAI_KEY=$(grep -A 3 '"zai-coding-plan"' "$AUTH_FILE" | grep '"key"' | sed 's/.*"key"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' 2>/dev/null || echo "")
            local ZHIPU_KEY=$(grep -A 3 '"zhipuai-coding-plan"' "$AUTH_FILE" | grep '"key"' | sed 's/.*"key"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' 2>/dev/null || echo "")
            
            if [ -z "$ZAI_KEY" ] || [ -z "$ZHIPU_KEY" ]; then
                NEED_API_KEY=true
                info_msg "API key is empty in auth.json"
            else
                success_msg "API key found in auth.json"
            fi
        fi
    fi
    
    # Prompt for API key if needed
    if [ "$NEED_API_KEY" = true ]; then
        echo ""
        warning_msg "请输入 API Key，用于 zai-coding-plan 和 zhipuai-coding-plan"
        info_msg "同一个 key 可同时用于两个服务"
        echo ""
        
        local INPUT_API_KEY=$(prompt_for_value "API Key")
        
        # Create auth.json with the key
        cat > "$AUTH_FILE" << EOF
{
  "zai-coding-plan": {
    "type": "api",
    "key": "${INPUT_API_KEY}"
  },
  "zhipuai-coding-plan": {
    "type": "api",
    "key": "${INPUT_API_KEY}"
  }
}
EOF
        chmod 600 "$AUTH_FILE"
        success_msg "API Key saved to auth.json"
    fi
}

# Main orchestrator: Validate all environment variables
validate_all_env_vars() {
    info_msg "Checking environment configuration..."
    validate_env_file_vars
    validate_auth_json_key
}

# Function to check if container is running
is_container_running() {
    docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"
}

# Function to check if container exists (running or stopped)
container_exists() {
    docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"
}

# Function to clean macOS AppleDouble files (causes Docker build failure on external volumes)
clean_appledouble() {
    local count=$(find "$SCRIPT_DIR" -name "._*" -type f 2>/dev/null | wc -l | tr -d ' ')
    if [ "$count" -gt 0 ]; then
        info_msg "Cleaning $count AppleDouble file(s) (macOS metadata on external volume)..."
        find "$SCRIPT_DIR" -name "._*" -type f -delete 2>/dev/null
        success_msg "AppleDouble files cleaned"
    fi
}

# Parse arguments
FORCE_RESTART=false
FORCE_REBUILD=false
FORCE_REBUILD_CACHE=false
while [[ $# -gt 0 ]]; do
    case $1 in
        -r|--restart)
            FORCE_RESTART=true
            shift
            ;;
        --rebuild)
            FORCE_REBUILD_CACHE=true
            shift
            ;;
        --rebuild-no-cache)
            FORCE_REBUILD=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  -r, --restart      Restart the container if it's already running"
            echo "  --rebuild          Stop, rebuild (with cache), and start the container"
            echo "  --rebuild-no-cache Stop, rebuild (no-cache), and start the container"
            echo "  -h, --help         Show this help message"
            echo ""
            echo "This script will:"
            echo "  1. Validate required environment variables"
            echo "  2. Prompt for missing credentials"
            echo "  3. Start, restart, or rebuild the Docker container"
            exit 0
            ;;
        *)
            error_exit "Unknown option: $1\nUse -h or --help for usage information"
            ;;
    esac
done

cd "$SCRIPT_DIR"

ENV_FILE="$SCRIPT_DIR/.env"

validate_all_env_vars

info_msg "Checking container status..."

if [ "$FORCE_REBUILD" = true ]; then
    info_msg "Stopping container..."
    docker-compose down
    
    clean_appledouble
    
    info_msg "Rebuilding container (no-cache)..."
    docker-compose build --no-cache
    
    info_msg "Starting container..."
    docker-compose up -d
    success_msg "Container rebuilt and started successfully"
elif [ "$FORCE_REBUILD_CACHE" = true ]; then
    info_msg "Stopping container..."
    docker-compose down
    
    clean_appledouble
    
    info_msg "Rebuilding container (with cache)..."
    docker-compose build
    
    info_msg "Starting container..."
    docker-compose up -d
    success_msg "Container rebuilt and started successfully"
elif is_container_running; then
    if [ "$FORCE_RESTART" = true ]; then
        info_msg "Restarting container..."
        docker-compose restart
        success_msg "Container restarted successfully"
    else
        echo ""
        warning_msg "Container '$CONTAINER_NAME' is already running"
        read -p "Do you want to restart it? [y/N]: " RESTART_CHOICE
        
        case "$RESTART_CHOICE" in
            y|Y|yes|YES)
                info_msg "Restarting container..."
                docker-compose restart
                success_msg "Container restarted successfully"
                ;;
            *)
                info_msg "Keeping container running"
                success_msg "Container is running at http://localhost:4097"
                ;;
        esac
    fi
else
    # Container is not running
    if container_exists; then
        info_msg "Container exists but is not running, starting..."
    else
        info_msg "Building and starting container..."
    fi
    
    clean_appledouble
    
    docker-compose up -d --build
    success_msg "Container started successfully"
fi

# Step 3: Show status
echo ""
info_msg "Container status:"
docker-compose ps

echo ""
success_msg "Access OpenCode at: http://localhost:4097"
info_msg "To enter container: docker exec -it $CONTAINER_NAME bash"
info_msg "To view logs: docker-compose logs -f"
